version: '3.8'

services:
  comfyui:
    build:
      context: .
      dockerfile: comfy-dockerfile
    volumes:
      - ./database:/database
      - /usr/lib/wsl:/usr/lib/wsl
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
              
    stdin_open: true
    tty: true
    networks:
      - app_network
